sudo: required
language: node_js
node_js:
  - 10
cache: 
  directories:
    - node_modules

services:
  - docker 

before_install: 
  # install heroku CLI 
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh 
  # login to docker registries (dockerhub + heroku) 
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin  
  - docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
  
install: 
  # install deps 
  - npm install 

script: 
  - npm test 
  - npm build 
  # build docker images 
  - docker build -t ucheka22/zatec-frontend:v2 .
  - docker tag ucheka22/zatec-frontend:v2  registry.heroku.com/$HEROKU_APP_NAME/web 

deploy: 
  provider: script 
  script: 
    # push to dockerhub & heroku 
     docker push ucheka22/zatec-frontend:v2;
     docker push registry.heroku.com/$HEROKU_APP_NAME/web;
     heroku container:release web --app $HEROKU_APP_NAME
